### ISSUE TITLE
How to use multiple GPUs

### ISSUE THREAD

**Issue by cheolho** [Nanne/pytorch-NetVlad#13]
Do you have any advice on how to use multiple GPUs?

I tried `--nGPU=8` (>1), but I have the input of the pooling layer missing:
```
Traceback (most recent call last):
  File "main.py", line 537, in <module>
    train(epoch)
  File "main.py", line 138, in train
    vlad_encoding = model.pool(image_encoding)
  File "lib64/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "lib64/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'
```

It occurs in the middle of training.
I have observed that `--batchSize=1` gives always the error.
`--batchSize=2` or `--batchSize=8` work fine at first.
However, after some epochs, the number of violating negatives (maximally 10) becomes lower,
and it seems to trigger the error.

One interesting point is that the error does not occur at the base model (e.g., vgg16).

**Comment by Nanne** [comment]
I can see how the filtering for violating negatives can lead to a batch with fewer than 8 samples, but it indeed doesn't make sense that it only happens for pooling, and not for the encoder. 

Could you try it with --batchSize=1 (if that is the same error), and then just printing the shape of the `input` fed to the encoder, and the shape of the `image_encoding` fed to the pooling? 

The docs for DataParallel do indicate that the batch size should be greater than the number of GPU, but I'd be surprised if the batch size became smaller after passing through the encoder..

**Comment by cheolho** [comment]
In short, `input` and `image_encoding` have the **same batch size**. For details, see below.

1. `--nGPU=5`, `--batchSize=1`, `--cacheBatchSize=24` 

I tried `--nGPU=5` and `--batchSize=1` and got the following while Building Cache (`--cacheBatchSize=24` as default):
```
input:
torch.Size([16, 3, 480, 640])
image_encoding:
torch.Size([16, 512, 30, 40])
image_encoding_prev: # which is the successful image_encoding right before the error occurs
torch.Size([24, 512, 30, 40])
Traceback (most recent call last):
  File "main.py", line 648, in <module>
    train(epoch)
  File "main.py", line 146, in train
    raise e
  File "main.py", line 113, in train
    vlad_encoding = model.pool(image_encoding)
  File "lib64/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "lib64/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'
```

`input` and `image_encoding` have the same batch size of 16, but the error only occurs at the pooling layer.

2. `--nGPU=5`, `--batchSize=1`, `--cacheBatchSize=12` 
I got a similar result with `--cacheBatchSize=12`:
`input` and `image_encoding` have the same batch size of 12, but the error only occurs at the pooling layer.


3. `--nGPU=4`, `--batchSize=1`, `--cacheBatchSize=24`
Similarly, in the middle of training (after some iterations), `input` and `image_encoding` have the same batch size of 5, but the error only occurs at the pooling layer.

```
input:
torch.Size([5, 3, 480, 640])
image_encoding:
torch.Size([5, 512, 30, 40])
image_encoding_prev:
torch.Size([12, 512, 30, 40])
query:
torch.Size([1, 3, 480, 640])
positives:
torch.Size([1, 3, 480, 640])
negatives:
torch.Size([3, 3, 480, 640])
```

**Comment by Nanne** [comment]
The cacheBatchSize shouldn't have an influence on this, as that always gives back a full batch. Although the last batch for the epoch might be smaller, but I guess you could set `drop_last` to `True` for the caching dataloader just to debug.

Nonetheless, 16 is still much bigger than 5, so it should have sufficient samples to divide across the GPU's. 

Given that it only happens during pooling you could also combine the encoder and pooling in a new `nn.Sequential`, and then only wrap that in a DataParallel, rather than having two separate DataParallel's.

**Comment by cheolho** [comment]
Yes, I may give it a try. Thank you for your help.
