### ISSUE TITLE
Unexpected key(s) in state_dict: "pool.centroids", "pool.conv.weight".

### ISSUE THREAD

**Issue by DonMuv** [Nanne/pytorch-NetVlad#54]
When i run the cluster, i got the problem:

Traceback (most recent call last):
  File "main.py", line 486, in <module>
    model.load_state_dict(checkpoint['state_dict'])
  File "/home/wwu/anaconda3/envs/UWSOD/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Module:
        Unexpected key(s) in state_dict: "pool.centroids", "pool.conv.weight". 

I need help

**Comment by DaddyWesker** [comment]
So, how did you managed to solve this?
