### ISSUE TITLE
Faiss k-means clustering error while calculating the optimal cluster centroids

### ISSUE THREAD

**Issue by SharangKaul123** [Nanne/pytorch-NetVlad#60]
Hey! I am getting an error in reference to Faiss while computing the optimal no. of clusters.  I have not changed anything and trying to run the code on the same dataset (Pittsburg 250k). What could this error possibly lead to? Because for my case, I already have the output in float32 format. Also, I am running the cluster mode for now at the beginning before the training mode according to the repository. I also went through this (https://github.com/facebookresearch/faiss/issues/1417). But don't know where is the error coming from?

Faiss version: Faiss-gpu 1.6.3
OS: Ubuntu 18.04 LTS
Anaconda: 4.10.3
PyTorch: 1.0.1.post2

===> Loading dataset(s)
===> Building model
===> Calculating descriptors and clusters
====> Extracting Descriptors
====> Clustering..
Traceback (most recent call last):
File "main.py", line 496, in
get_clusters(whole_train_set)
File "main.py", line 279, in get_clusters
kmeans.train(dbFeat[...])
File "/home/kau4hi/gpu_anaconda3/lib/python3.6/site-packages/faiss/init.py", line 734, in train
clus.train(x, self.index, weights)
File "/home/kau4hi/gpu_anaconda3/lib/python3.6/site-packages/faiss/init.py", line 85, in replacement_train
self.train_c(n, swig_ptr(x), index)
File "/home/kau4hi/gpu_anaconda3/lib/python3.6/site-packages/faiss/swigfaiss_avx2.py", line 1477, in train
return _swigfaiss_avx2.Clustering_train(self, n, x, index, x_weights)
NotImplementedError: Wrong number or type of arguments for overloaded function 'Clustering_train'.
Possible C/C++ prototypes are:
faiss::Clustering::train(faiss::Clustering::idx_t,float const *,faiss::Index &,float const *)
faiss::Clustering::train(faiss::Clustering::idx_t,float const *,faiss::Index &)

**Comment by SharangKaul123** [comment]
As suggested, the data type of variable taken by kmeans.train() function has to kept as float32. Just look through the particular function you are operating on in your file.
